import { z } from "zod";

export const singleProductPromotion = z.object({
  type: z.literal("SINGLE_PRODUCT_PROMOTION"),
  id: z.string(),
  from_shakeomat: z.boolean(),
  name: z.string(),
  details: z.string(),
  description: z.string().or(z.null()),
  limit_message: z.string().or(z.null()),
  limit_message_short: z.string().or(z.null()),
  start: z.string(),
  end: z.string(),
  image_url: z.string(),
  highlighted: z.boolean(),
  price_tag_info: z.string(),
  unit: z.string(),
  price: z.string(),
  unit_price: z.string(),
  regular_price: z.string(),
  regular_unit_price: z.string(),
  omnibus_price: z.string(),
  omnibus_unit_price: z.string(),
  omnibus_type: z.string(),
  discount: z.number(),
  discount_to_omnibus_price: z.number(),
  several_regular_prices: z.boolean(),
  only_with_moja_biedronka_card: z.boolean(),
  product_main_ean_code: z.string(),
  ext_id: z.string().or(z.null()),
  promotion_type: z.string(),
});

export const promosCarouselsDetails = z.object({
  id: z.string(),
  type: z.string(),
  name: z.string(),
  title: z.string(),
  image_url: z.null().or(z.string()),
  external_url: z.null().or(z.string()),
  items: z.array(
    z.discriminatedUnion("type", [
      z.object({
        type: z.literal("STATIC_CONTENT"),
        id: z.string(),
        start: z.string(),
        end: z.string(),
        image_url: z.string(),
        url: z.string(),
      }),
      singleProductPromotion,
      z.object({
        type: z.literal("SHAKEOMAT_2"),
        offer_id: z.string(),
        available_from: z.string(),
      }),
      z.object({
        type: z.literal("ACTION"),
        id: z.string(),
        from_shakeomat: z.boolean(),
        name: z.null().or(z.string()),
        details: z.string(),
        limit_message: z.null().or(z.string()),
        limit_message_short: z.null().or(z.string()),
        image_url: z.string(),
        start: z.string(),
        end: z.string(),
        only_with_moja_biedronka_card: z.boolean(),
        mix_freely: z.boolean(),
        ext_id: z.string(),
        description: z.null().or(z.string()),
      }),
    ])
  ),
});
